import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/banner'

const inter = Inter({ subsets: ['latin'] });
const handleOnBannerBtnClick = () => {
  alert('banner btn')
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.heroBanner}>
          <Banner buttonText="Visit stores nearby" handleOnClick={handleOnBannerBtnClick}  />
          <Image
            src="/static/coffee-cup.png"
            alt='a coffee cup'
            width={400}
            height={400}
            className= {styles.heroImage}
          />
        </div>
      </main>
    </>
  )
};
